name: CI

on: [push, pull_request]

jobs:
  macos:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Install MacPorts
      run: |
        curl -L -O "https://github.com/macports/macports-base/releases/download/v2.10.1/MacPorts-2.10.1-14-Sonoma.pkg"
        sudo installer -store -pkg MacPorts-2.10.1-14-Sonoma.pkg -target /
        echo "file://$PWD [nosync]" | sudo tee -a /opt/local/etc/macports/sources.conf
    - name: Make packages
      run: |
        export PATH=$PATH:/opt/local/bin
        sudo rm -rf /usr/local/*
        sudo portindex
        sudo port -v selfupdate && sudo port mpkg libswiften
        echo "workdir=$(port work libswiften)" >> $GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.workdir }}/libswiften-4.0.mpkg
